index:
    path: /
    methods: GET
    controller: SmartAPI\Controller\BaseController::index
ddns-create:
    path: /ddns
    methods: POST
    controller: SmartAPI\Controller\DynamicDNS::create
ddns-update:
    path: /ddns
    methods: PUT
    controller: SmartAPI\Controller\DynamicDNS::update
ifttt-status:
    path: /ifttt/v1/status
    methods: GET
    controller: SmartAPI\Controller\IFTTT::status
ifttt-setup:
    path: /ifttt/v1/test/setup
    methods: POST
    controller: SmartAPI\Controller\IFTTT::setup
ifttt-wol_pcd:
    path: /ifttt/v1/actions/wol_pcd
    methods: POST
    controller: SmartAPI\Controller\Actions::wakeOnLan
