index:
    path: /
    methods: GET
    controller: SmartAPI\Controller\BaseController::index
ddns:
    path: /ddns
    methods: POST
    controller: SmartAPI\Controller\DynamicDNS::update
ifttt-setup:
    path: /ifttt/v1/test/setup
    methods: GET
    controller: SmartAPI\Controller\IFTTT::setup
ifttt-wol_pcd:
    path: /ifttt/v1/actions/wol_pcd
    methods: POST
    controller: SmartAPI\Controller\Actions::wakeOnLan
