index:
    path: /
    methods: GET
    controller: SmartAPI\Controller\BaseController::index
ddns:
    path: /ddns
    methods: POST
    controller: SmartAPI\Controller\DynamicDNS::update
wol:
    path: /wol
    methods: POST
    controller: SmartAPI\Controller\Actions::wakeOnLan
